title:              혼공
email:              syeonki66@gmail.com
description:        나 혼자 공부하는 블로그
author:             syki66
baseurl:            "/syki-blog"
url:                "https://syki66.github.io"

# Social Profiles
#twitter_username:   SBootstrap
github_username:    syki66
#facebook_username:  StartBootstrap
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           10
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

highlighter: rouge